### ISSUE TITLE
Turning mocking service off and on again adds extra "mocks/<guid>" to the base URI

### ISSUE THREAD

**Issue by melissavdh** [mulesoft/api-designer#297]
When I first turn on the mocking service the base URI in my RAML becomes:
http://mocksvc.mulesoft.com/mocks/0a7ebfb8-f2c3-4c52-a68b-e8705292e539/api
(1st time on: 1 x "/mocks" in URI)

If I turn it off and on again it is now:
http://mocksvc.mulesoft.com/mocks/8b854c1c-cd4f-4c29-9aa0-b9317e29b262/mocks/0a7ebfb8-f2c3-4c52-a68b-e8705292e539/api
(2nd time on: 2 x "/mocks" in URI)

If I repeat I get:
http://mocksvc.mulesoft.com/mocks/4035efce-4dcd-4f6b-ae2d-04e0149fc445/mocks/8b854c1c-cd4f-4c29-9aa0-b9317e29b262/mocks/0a7ebfb8-f2c3-4c52-a68b-e8705292e539/api
(3rd time on: 3 x "/mocks" in URI)

Note how each time I turn it off and on, the base URI includes the whole of the previous base URI from the last time the mocking service was on.

**Comment by dmartinezg** [comment]
Hi @melissavdh, thanks for reporting this, we'll take a look at what the mocking service is doing, and why this happens.

**Comment by sichvoge** [comment]
Waiting for about 30sec helps - it happens when you immediately switch it on, off, and on again.

**Comment by sichvoge** [comment]
Still an issue!

**Comment by carowright** [comment]
Already fixed in develop branch. Will be released in next version.

**Comment by sichvoge** [comment]
you sure its fixed? still happens for me on the develop branch. See this URL that contains two different `mocks`:

baseUri: http://ec2-52-201-242-128.compute-1.amazonaws.com/mocks/ebf83e4d-0ab6-4d71-870d-3216d957e497/mocks/e01fec5d-bb06-46a4-888a-912b33a597c3

Reproduce:

1. take any RAML file
2. press enable mocking service button
3. press disable mocking service button
4. press enable again

the enable and disable should be pressed with a short duration in between.

**Comment by carowright** [comment]
Sorry, it was in a different branch. Now it is in develop.
